Simplify workflows and dockerfiles
karpatkey/panic-button-app pull request #414
Opened 2024-02-15 16:37 UTC by sanekto

@dharmendrakariya The kubernetes config must have a new environment variable defined for the production deployment:
`PBA_ENV=production`

That way the run.sh script will run `yarn start` instead of `yarn dev`

2024-02-29 19:12 UTC, sanekto commented
Is there anything blocking this?

2024-03-01 06:27 UTC, dharmendrakariya commented
Hey @sanekto  overall it looks good to me, specially the dockerfile changes but for CI we want one more tag , branch name as tag! please add `type=ref,event=branch` and we are good! 

Also would like to ask @sgzerbo  if he is okay with this logic (reason I have duplication of Dockerfiles in all repos is that we want to keep everything way simpler and easy to understand for each tech guy) I believe this is also simple but just want his confirmation and we can merge it!

2024-03-01 06:29 UTC, dharmendrakariya commented on Dockerfile
We need to copy the run.sh here

2024-03-01 06:30 UTC, dharmendrakariya requested changes
after the required changes, we are good!

2024-03-01 06:30 UTC, dharmendrakariya commented on .github/workflows/docker.yml
We have to add tag (branch name)

2024-03-04 11:53 UTC, dharmendrakariya approved these changes

2024-03-04 12:56 UTC, ismaelga approved these changes

2024-03-04 13:12 UTC, dharmendrakariya commented
@sanekto  @sgzerbo  we can merge this! I have tested this images and working fine!

2024-03-04 13:52 UTC, sanekto commented
Great, thanks for taking care. 

The last commits show why I beleive using github actions (docker/metadata-action@v5, actions/checkout@v4, etc) is flawed, even if github promotes it. It is something that really adds confusion and it is not locally reproducible so it adds a lot of work and debugging time instead of reducing it. And it also does vendor lock-in (that is why I believe github promotes it). 
For the future I suggest to do a script based approach, something like https://github.com/karpatkey/roles_royce/blob/main/.github/scripts/build_and_push.sh . It is easier to reproduce locally (just provide a couple of env variables) and there is no "magic" just a plain script that everyone can read and understand. Even if we add all the cool things like caching etc it is in something approachable.

2024-03-04 14:30 UTC, dharmendrakariya commented
@sanekto  bro totally agree with you, just to add the simple branch name as a tag I was struggling and there is no way we can debug this locally! I like your idea! We shall move to the shell scripting! I saw your changes in roles_royce! Similar approach we can adapt here! wdyt?

2024-03-04 19:49 UTC, sanekto commented
Yes I think a similar approach can be done here (in another PR). 
Merge this one whenever you like.

2024-03-06 17:30 UTC, ismaelga commented
@sanekto @dharmendrakariya I actually think we could run prod build in these preview envs, meaning that way we wouldn't need that script and the new env var

2024-03-06 20:03 UTC, sanekto commented
I don't know the diff between the two versions, I never run the app myself. So I am +1 on whatever you think is best.

2024-03-08 05:59 UTC, dharmendrakariya commented
@ismaelga  we want to run develop images in PR-review deployments! could you create a separate PR with your commits bro?
I think we shall merge this branch without your changes as of now!

2024-03-08 10:45 UTC, ismaelga commented
@dharmendrakariya I'll remove my changes but keep in mind the build wasn't working properly. You still need to fix it after

2024-03-08 13:24 UTC, merged